name: Terraform Security & Validation

on:
  push:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-checkov:
    name: Checkov Check
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout do Repositório
        uses: actions/checkout@v4

      - name:  Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-2"          

      - name:  Instalar Checkov (Escaneamento de Segurança)
        run: |
          echo " Instalando Checkov..."
          pip install checkov
          checkov --version

      - name:  Inicializar Terraform (`terraform init`)
        run: terraform init

      - name:  Rodar Checkov (Segurança de Infraestrutura)
        run: |
          echo " Rodando Checkov para escanear a segurança do código Terraform..."
          checkov -d . --quiet --compact || echo " Erros de segurança encontrados! Corrija antes de continuar."
