name: gitleaks
on: [pull_request]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install TruffleHog
        run: mkdir sec && cd sec && curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | sh -s -- -b /usr/local/bin
  
      - name: Secret Scanning with TruffleHog
        run: |
              trufflehog -h
              trufflehog filesystem ./
